name: disney_plus
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.8
  flutter_bloc: ^7.3.2
  equatable: ^2.0.3
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/movies.json
    - assets/images/logos/
    - assets/images/category_logos/
    - assets/images/movies/avengers/
    - assets/images/movies/avengers_age_of_ultron/
    - assets/images/movies/avengers_infinity_war/
    - assets/images/movies/avengers_endgame/
    - assets/images/movies/the_falcon_and_the_winter_soldier/
    - assets/images/movies/loki/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
